---
- hosts: sns00
  become: True
  remote_user: viewadmin
  become_method: sudo
<<<<<<< HEAD
  become_user: rott
=======
  become_user: root
  vars:
    ansible_become_password: "***sudo password here***"
>>>>>>> upstream/main
  tasks:
    #    - name: Generate key
    #  openssh_keypair:
    #    path: app
<<<<<<< HEAD
    - name: Create userc
=======
    - name: Create user
>>>>>>> upstream/main
      user:
        name: app
        home: /home/app
        generate_ssh_key: no
    - name: Assert .ssh directory
      file:
        dest: /home/app/.ssh
        state: directory
        owner: app
        mode: '0700'
    - name: Install public SSH key
      copy:
        src: app.pub
        dest: /home/app/.ssh/app.pub
        owner: app
        mode: '0600'
    - name: Install authorized key
      authorized_key:
        user: app
        state: present
<<<<<<< HEAD
        key: "{{ lookup('file', 'app.pub') }}"
=======
        key: "{{ lookup('file', 'app.pub') }}"
>>>>>>> upstream/main
